openapi: 3.1.1
info:
  title: Manage Docs
  description: |-
    社内向けドキュメント管理システムのAPIの仕様
  version: 1.0.0
servers:
  - url: http://localhost/api/v1
paths:
    /organizations/{organization_id}/articles:
      get:
        summary: 記事一覧取得
        tags:
          - Articles
        security:
          - BearerAuth: []
        parameters:
          - name: organization_id
            in: path
            required: true
            schema:
              type: string
              format: uuid
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    articles:
                      type: array
                      items:
                        $ref: '#/components/schemas/ArticleOverview'
          '401':
            description: Unauthorized
          '404':
            description: Organization not found
          '403':
            description: Forbidden
          '500':
            description: Internal Server Error
components:
  schemas:
    ArticleOverview:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 記事のID
          example: "aa687d47-b976-4a9a-87cc-19ec205c3ff9"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWTトークンによる認証

  
